name = "Trees"
uuid = "d3549d90-f74a-11e8-3813-3bb8358dfa17"
authors = ["Cecile Ane <cecileane@users.noreply.github.com>"]
version = "0.1.0"

[deps]
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
